apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-ex-lgvi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-ex-lgvi
    app.kubernetes.io/part-of: my-app
  name: nodejs-ex-lgvi
  namespace: user1-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: nodejs-ex-lgvi
    weight: null
status: {}
