apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-ex-lgvi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-ex-lgvi
    app.kubernetes.io/part-of: my-app
  name: nodejs-ex-lgvi
  namespace: user1-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: nodejs-ex-lgvi
status:
  loadBalancer: {}
